### ISSUE TITLE
Empty req.body

### ISSUE THREAD

**Issue by reardestani** [domharrington/fileupload#13]
Hi,

I am using Express 4 and have installed your module as you mentioned in docs but it gives and empty `req.body`, consider that I have used `enctype="multipart/form-data"` on my form and if I remove the `enctype`, it shows the `req.body` like below which is not useful.

```
{
"title": "sample title",
"description": "amsple long description",
"video": "video.mp4"
}
```

Should I add `enctype` to form or not? 

Please provide a complete example in docs.

**Comment by domharrington** [comment]
Hi,

Thanks for using my module. I would actually recommend using https://www.npmjs.com/package/multer instead of this module. It has been supported much better recently and would be my first choice.

I will add a deprecation notice to the readme. 

Thanks.
